Repository AntonioJavierRP/Informatica-grafica-IG-, pull requests merged in 2020-10, with the labels that each got.

#2 Practica 2 IG
  Practica_2/Makefile
  Practica_2/ant.ply
  Practica_2/beethoven.ply
  Practica_2/cat.ply
  Practica_2/include/O3D.h
  Practica_2/include/O3DR.h
  Practica_2/include/O3DS.h
  Practica_2/include/PlyReader.h
  Practica_2/include/cilindro.h
  Practica_2/include/cono.h
  Practica_2/include/cubo.h
  Practica_2/include/esfera.h
  Practica_2/include/file_ply_stl.h
  Practica_2/include/piramide.h
  Practica_2/include/tetraedro.h
  Practica_2/include/tubo.h
  Practica_2/include/vaso.h
  Practica_2/include/vaso_inv.h
  Practica_2/include/vertex.h
  Practica_2/lib/libFiguras.a
  Practica_2/perfil.ply
  Practica_2/src/O3D.cpp
  Practica_2/src/O3DR.cpp
  Practica_2/src/O3DS.cpp
  Practica_2/src/PlyReader.cpp
  Practica_2/src/cilindro.cpp
  Practica_2/src/cono.cpp
  Practica_2/src/cubo.cpp
  Practica_2/src/esfera.cpp
  Practica_2/src/file_ply_stl.cc
  Practica_2/src/piramide.cpp
  Practica_2/src/practica2.cpp
  Practica_2/src/tetraedro.cpp
  Practica_2/src/tubo.cpp
  Practica_2/src/vaso.cpp
  Practica_2/src/vaso_inv.cpp
Labels: bug

#3 documentation
  .gitignore
  README.md
Labels: documentation, hacktoberfest-accepted

#4 Practica 3 - IG
  Practica_3/Makefile
  Practica_3/ant.ply
  Practica_3/beethoven.ply
  Practica_3/cat.ply
  Practica_3/img/Practica_3.png
  Practica_3/include/O3D.h
  Practica_3/include/O3DR.h
  Practica_3/include/O3DS.h
  Practica_3/include/PlyReader.h
  Practica_3/include/base.h
  Practica_3/include/block.h
  Practica_3/include/bloque_central.h
  Practica_3/include/brazo.h
  Practica_3/include/cilindro.h
  Practica_3/include/cono.h
  Practica_3/include/cubo.h
  Practica_3/include/esfera.h
  Practica_3/include/esqueleto.h
  Practica_3/include/file_ply_stl.h
  Practica_3/include/parte_arriba.h
  Practica_3/include/piramide.h
  Practica_3/include/regulador.h
  Practica_3/include/tetraedro.h
  Practica_3/include/tubo.h
  Practica_3/include/vaso.h
  Practica_3/include/vaso_inv.h
  Practica_3/include/vertex.h
  Practica_3/lib/libFiguras.a
  Practica_3/perfil.ply
  Practica_3/src/O3D.cpp
  Practica_3/src/O3DR.cpp
  Practica_3/src/O3DS.cpp
  Practica_3/src/PlyReader.cpp
  Practica_3/src/base.cpp
  Practica_3/src/block.cpp
  Practica_3/src/bloque_central.cpp
  Practica_3/src/brazo.cpp
  Practica_3/src/cilindro.cpp
  Practica_3/src/cono.cpp
  Practica_3/src/cubo.cpp
  Practica_3/src/esfera.cpp
  Practica_3/src/esqueleto.cpp
  Practica_3/src/file_ply_stl.cc
  Practica_3/src/parte_arriba.cpp
  Practica_3/src/piramide.cpp
  Practica_3/src/practica3.cpp
  Practica_3/src/regulador.cpp
  Practica_3/src/tetraedro.cpp
  Practica_3/src/tubo.cpp
  Practica_3/src/vaso.cpp
  Practica_3/src/vaso_inv.cpp
Labels: enhancement, hacktoberfest-accepted

#5 Fixing some errors naming folders and in doc
  Practica 2/Makefile
  Practica 2/ant.ply
  Practica 2/beethoven.ply
  Practica 2/cat.ply
  Practica 2/include/O3D.h
  Practica 2/include/O3DR.h
  Practica 2/include/O3DS.h
  Practica 2/include/PlyReader.h
  Practica 2/include/cilindro.h
  Practica 2/include/cono.h
  Practica 2/include/cubo.h
  Practica 2/include/esfera.h
  Practica 2/include/file_ply_stl.h
  Practica 2/include/piramide.h
  Practica 2/include/tetraedro.h
  Practica 2/include/tubo.h
  Practica 2/include/vaso.h
  Practica 2/include/vaso_inv.h
  Practica 2/include/vertex.h
  Practica 2/lib/libFiguras.a
  Practica 2/perfil.ply
  Practica 2/src/O3D.cpp
  Practica 2/src/O3DR.cpp
  Practica 2/src/O3DS.cpp
  Practica 2/src/PlyReader.cpp
  Practica 2/src/cilindro.cpp
  Practica 2/src/cono.cpp
  Practica 2/src/cubo.cpp
  Practica 2/src/esfera.cpp
  Practica 2/src/file_ply_stl.cc
  Practica 2/src/piramide.cpp
  Practica 2/src/practica2.cpp
  Practica 2/src/tetraedro.cpp
  Practica 2/src/tubo.cpp
  Practica 2/src/vaso.cpp
  Practica 2/src/vaso_inv.cpp
  README.md
Labels: bug, documentation, hacktoberfest-accepted

#6 documentation p3
  README.md
Labels: documentation, hacktoberfest-accepted
